project_name: fastschema
dist: releases

version: 1

before:
  hooks:
    - go mod tidy
    - make builddash

builds:
  - id: build_default
    main: ./default
    binary: fastschema
    flags:
      - -trimpath
    ldflags:
      - -s -w -X fastschema.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

archives:
  - id: build_default
    format: zip

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
