project_name: fastschema
dist: releases

version: 1

before:
  hooks:
    - go mod tidy
    - make builddash

builds:
  - id: build_default
    main: ./default
    binary: fastschema
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - id: build_default
    format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
